server:
  port: 8080
spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:sqlserver://promptmaster-sql-server.database.windows.net:1433;database=mydatabase;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: enriqueRoot@promptmaster-sql-server
    password: TaMaRa1726
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000 
      max-lifetime: 1200000
      connection-test-query: SELECT 1
      validation-timeout: 5000