server:
  port: 8080
spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:mysql://promptmaster-db-mysql.mysql.database.azure.com:3306/mydatabase?useSSL=true&enabledTLSProtocols=TLSv1.2
    username: enrique
    password: TaMaRa1726
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 30000
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      continue-on-error: true
  application:
    name: backend
  websocket:
    enabled: true

# Add logging for debugging connection issues
logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG