server:
  port: 8080
spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:sqlserver://promptmaster-sql-server.database.windows.net:1433;database=mydatabase;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: enriqueRoot@promptmaster-sql-server
    password: TaMaRa1726
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      keepalive-time: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    database-platform: org.hibernate.dialect.SQLServerDialect
  sql:
    init:
      mode: always
      continue-on-error: true
  application:
    name: backend
  websocket:
    enabled: true

# Detailed logging configuration
logging:
  level:
    root: INFO
    info.sup.proj.backend: DEBUG
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    # org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: DEBUG
    org.hibernate.type: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application specific configuration
app:
  cors:
    allowed-origins: https://localhost:5173,https://promptmaster-frontend.braveforest-8e4d5d0c.westeurope.azurecontainerapps.io
  initialization:
    force: false