name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: azure-deploy
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Make Maven wrapper executable
      run: chmod +x ./backend/mvnw
        
    - name: Build backend with Maven
      run: |
        cd backend
        ./mvnw clean package -DskipTests
        
    - name: Build frontend
      run: |
        cd frontend
        npm ci
        npm run build
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure CLI using Service Principal
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
        
    - name: Log in to Azure Container Registry
      run: |
        az acr login --name promptmasterregistry

    - name: Build and push Docker image to Azure Container Registry
      run: |
        docker build -t promptmasterregistry.azurecr.io/backend:latest ./backend
        docker build -t promptmasterregistry.azurecr.io/frontend:latest ./frontend
        docker push promptmasterregistry.azurecr.io/backend:latest
        docker push promptmasterregistry.azurecr.io/frontend:latest

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name promptmaster-frontend \
          --resource-group ISNL_AIGame_EnriqueB \
          --image promptmasterregistry.azurecr.io/frontend:latest \
          --cpu 1 --memory 2Gi
          
        az containerapp ingress update \
          --name promptmaster-frontend \
          --resource-group ISNL_AIGame_EnriqueB \
          --type external \
          --target-port 8081
        
        az containerapp update \
          --name promptmaster-backend \
          --resource-group ISNL_AIGame_EnriqueB \
          --image promptmasterregistry.azurecr.io/backend:latest \
          --cpu 1 --memory 2Gi
          
        az containerapp ingress update \
          --name promptmaster-backend \
          --resource-group ISNL_AIGame_EnriqueB \
          --type external \
          --target-port 8080