name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push Docker image to Azure Container Registry
      run: |
        docker build -t promptmasterregistry.azurecr.io/promptmaster-backend:latest ./backend
        docker build -t promptmasterregistry.azurecr.io/promptmaster-frontend:latest ./frontend
        docker push promptmasterregistry.azurecr.io/promptmaster-backend:latest
        docker push promptmasterregistry.azurecr.io/promptmaster-frontend:latest

    - name: Azure CLI Setup
      uses: azure/setup-azurecli@v1

    - name: Login to Azure CLI
      uses: azure/cli-action@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name promptmaster-frontend \
          --resource-group ISNL_AIGame_EnriqueB \
          --image promptmasterregistry.azurecr.io/promptmaster-frontend:latest \
          --cpu 1 --memory 2Gi \
          --ingress 'external' \
          --target-port 8081
        
        az containerapp update \
          --name promptmaster-backend \
          --resource-group ISNL_AIGame_EnriqueB \
          --image promptmasterregistry.azurecr.io/promptmaster-backend:latest \
          --cpu 1 --memory 2Gi \
          --ingress 'external' \
          --target-port 8080
